package chapter_1;

/************************************************************************************
 * This program is written for Computer Science: Programming with a Purpose
 * course on coursera linked below
 * @Link - https://www.coursera.org/learn/cs-programming-java/home/welcome
 * The programs contain examples, solutions to chapter exercises
 * programming assignments and are authored by
 *
 * @author Venkateshwara Gowru
 *
 * @Input - Input real number u and v
 *
 * @ProblemStatement - “Gaussian random numbers. Write a program RandomGaussian
 * that prints a random number r drawn from the Gaussian distribution.
 * One way to do so is to use the Box–Muller formula
 * r = sin(2 π v) (–2 ln u) pow 1/2
 * where u and v are real numbers between 0 and 1 generated by the Math.random() method.”
 *
 * @Output - r a random number drawn using Gaussian Distribution
 *
 ************************************************************************************/
public class Exercise_1_2_27 {
    public static void main(String[] args) {
        double u = Math.random();
        double v = Math.random();
        double r = (Math.sin(2 * Math.PI * v)) * (Math.pow((-2 * Math.log(u)), 1 / 2));
        System.out.println("Random number r: " + r);
    }
}
